### PR TITLE
Do not display "null" when values are set to null

### LINKED ISSUE #41: Fix values displayed as null
do not display `null` as default value for empty fields like:

- language
- username
- user bio
- company
- location

### PR DESCRIPTION
**Pull request by AceGentile**
Do not display `null` when some values (language, username, user bio, company, location etc) are set to null but set a default value.

This fixes #41

### CODE REVIEW

**Comment by ayan-b** [comment]
Thank you so much!

**Comment by ayan-b** [comment]
@AceGentile Please add your name to the CONTRIBUTORS file.

**Comment by ayan-b** [comment]
@AceGentile Sorry, but can you please reopen and change the head branch to gh-pages instead of master?

**Comment by AceGentile** [comment]
> @AceGentile Sorry, but can you please reopen and change the head branch to gh-pages instead of master?

sorry, I did'nt notice that `gh-pages` was the main branch, here's new PR https://github.com/ayan-b/GitHub-Activity-Checker/pull/49

**Pull request merged**
