### PR TITLE
fixes issue #37 Add velocity.js script

### PR DESCRIPTION
**Pull request by bigchenla**

### CODE REVIEW

**Comment by ayan-b** [comment]
Hi @bigchenla, Thanks for the PR. Can you try adding some tests using Selenium?

**Comment by ayan-b** [comment]
Please update the CONTRIBUTORS file as well.

**Comment by bigchenla** [comment]
Do you mean using saucelabs?

**Comment by ayan-b** [comment]
Thanks, I will merge the PR.

**Pull request merged**
